networks:
  app-network:
    driver: bridge

services:
  database:
    build:
      context: ./database
    volumes:
      - dbdata:/data/db
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./back-end
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongodb://database:27017/app_db  
    depends_on:
      - database
    networks:
      - app-network  
    restart: always

volumes:
  dbdata:


