networks:
  app-network:
    driver: bridge

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    restart: always
    environment:
      SERVER_API: https://contactmanagerteamone.one
    
  database:
    build:
      context: ./database
    volumes:
      - dbdata:/data/db
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./back-end
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongodb://database:27017/app_db  
    depends_on:
      - database
    networks:
      - app-network  
    restart: always

volumes:
  dbdata:


