// init-mongo.js

// Connect to 'app_db' database
db = db.getSiblingDB('app_db');

// Create a collection for users and insert a sample user with hashed password
db.createCollection('users');
db.users.insertOne({
    username: "sample_user",
    password: "$2b$10$samplehashpassword", // Replace with a hashed password generated by bcrypt
});

// Create a collection for sports games
db.createCollection('sports_games');
db.sports_games.insertOne({
    game_id: 1,
    team1: "Team A",
    team2: "Team B",
    score: { team1: 3, team2: 2 },
    date: new Date()
});

